In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
books= pd.read_csv("Books.csv")
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

C:\Users\MAYANK\AppData\Local\Temp\ipykernel_5124\3565690060.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books= pd.read_csv("Books.csv")


In [3]:
books.shape

(271360, 8)

In [4]:
users.shape

(278858, 3)

In [5]:
ratings.shape

(1149780, 3)

In [6]:
books.sample()

ISBN         Book-Title      Book-Author Year-Of-Publication  \
270564  0809249413  The Woman Cyclist  Elaine Mariolle                1988   

                             Publisher  \
270564  McGraw-Hill/Contemporary Books   

                                              Image-URL-S  \
270564  http://images.amazon.com/images/P/0809249413.0...   

                                              Image-URL-M  \
270564  http://images.amazon.com/images/P/0809249413.0...   

                                              Image-URL-L  
270564  http://images.amazon.com/images/P/0809249413.0...

In [7]:
ratings.sample()

User-ID        ISBN  Book-Rating
853328   206415  033375588X            0

In [8]:
users.sample()

User-ID                  Location   Age
24579    24580  toronto, ontario, canada  37.0

In [9]:
books.drop(["Image-URL-S","Image-URL-M","Image-URL-L"], axis=1, inplace=True)

In [10]:
books.sample()

ISBN     Book-Title   Book-Author Year-Of-Publication  \
181690  1860464475  Ports of Call  Amin Maalouf                1999   

            Publisher  
181690  Harvill Press

In [11]:
new= books.merge(ratings, on="ISBN")

In [12]:
new.shape

(1031136, 7)

In [13]:
books.shape

(271360, 5)

In [14]:
ratings.shape

(1149780, 3)

In [15]:
new_df=new.merge(users, on="User-ID")

In [16]:
new_df.sample()

ISBN                     Book-Title    Book-Author  \
347399  0842349065  Pocket Smiles: 777 Moldy Olds  Robert Savage   

       Year-Of-Publication          Publisher  User-ID  Book-Rating  \
347399                1984  Tyndale House Pub   225087            0   

                        Location   Age  
347399  toronto, ontario, canada  51.0

In [17]:
new_df.shape

(1031136, 9)

In [18]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031136 entries, 0 to 1031135
Data columns (total 9 columns):
 #   Column               Non-Null Count    Dtype  
---  ------               --------------    -----  
 0   ISBN                 1031136 non-null  object 
 1   Book-Title           1031136 non-null  object 
 2   Book-Author          1031134 non-null  object 
 3   Year-Of-Publication  1031136 non-null  object 
 4   Publisher            1031134 non-null  object 
 5   User-ID              1031136 non-null  int64  
 6   Book-Rating          1031136 non-null  int64  
 7   Location             1031136 non-null  object 
 8   Age                  753301 non-null   float64
dtypes: float64(1), int64(2), object(6)
memory usage: 70.8+ MB


In [19]:
new_df.isnull().sum()

ISBN                        0
Book-Title                  0
Book-Author                 2
Year-Of-Publication         0
Publisher                   2
User-ID                     0
Book-Rating                 0
Location                    0
Age                    277835
dtype: int64

In [20]:
new_df=new_df.rename({"Book-Title":"title", "Book-Author":"author", "Year-Of-Publication":"year","User-ID":"ID","Book-Rating":"Rating"}, axis=1)

In [21]:
new_df.sample()

ISBN                                              title  \
514865  0373707789  Texas Lawman  (The West Texans) (Harlequin Sup...   

                 author  year  Publisher      ID  Rating  \
514865  Ginger Chambers  1998  Harlequin  172030       0   

                        Location   Age  
514865  rainsville, alabama, usa  30.0

In [22]:
new_df.Rating.unique()

array([ 0,  5,  6,  7,  9,  8, 10,  3,  1,  4,  2], dtype=int64)

In [23]:
x=new_df.ID.value_counts()>200

In [24]:
y=x[x].index

In [25]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       196047, 240567, 142093, 207782, 178199, 246311, 164323, 201783, 214272,
       269890],
      dtype='int64', name='ID', length=811)

In [26]:
new_df=new_df[new_df.ID.isin(y)]

In [27]:
new_df.shape

(474007, 9)

In [28]:
number_rating=new_df.groupby("title").count()["Rating"].reset_index()

In [29]:
number_rating.rename(columns={"Rating":"num_of_ratings"},inplace=True)

In [30]:
number_rating

title  num_of_ratings
0        A Light in the Storm: The Civil War Diary of ...               2
1                                   Always Have Popsicles               1
2                    Apple Magic (The Collector's series)               1
3        Beyond IBM: Leadership Marketing and Finance ...               1
4        Clifford Visita El Hospital (Clifford El Gran...               1
...                                                   ...             ...
155840                             Ã?Â?ber das Fernsehen.               2
155841  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...               3
155842                                      Ã?Â?lpiraten.               1
155843                              Ã?Â?stlich der Berge.               1
155844                                  Ã?Â?thique en toc               1

[155845 rows x 2 columns]

In [31]:
new_df.sample()

ISBN      title       author  year    Publisher      ID  Rating  \
92734  0451208072  St. Raven  Jo Beverley  2003  Signet Book  143253       0   

                        Location   Age  
92734  dyersburg, tennessee, usa  27.0

In [32]:
final_df= new_df.merge(number_rating, on="title")

In [33]:
final_df.sample()

ISBN       title      author  year      Publisher      ID  \
129925  0316588741  Demonology  Rick Moody  2001  Little, Brown  129716   

        Rating                   Location   Age  num_of_ratings  
129925       0  tallahassee, florida, usa  30.0               3

In [34]:
final_df.shape

(474007, 10)

In [35]:
final_df=final_df[final_df.num_of_ratings>=50]

In [36]:
final_df.shape

(58586, 10)

In [37]:
final_df.drop_duplicates(["ID", "title"], inplace=True)

In [38]:
final_df.shape

(56629, 10)

In [39]:
final_df.Age.isnull().sum()

12571

In [40]:
final_df.title= final_df.title.apply(lambda x: x.lower())

In [41]:
pt=final_df.pivot_table(columns="ID", index="title", values="Rating")

In [42]:
pt

ID                                                  254     2276    2766    \
title                                                                        
1984                                                   9.0     NaN     NaN   
1st to die: a novel                                    NaN     NaN     NaN   
2nd chance                                             NaN    10.0     NaN   
4 blondes                                              NaN     NaN     NaN   
\o\" is for outlaw"                                    NaN     NaN     NaN   
...                                                    ...     ...     ...   
wuthering heights                                      NaN     NaN     NaN   
year of wonders                                        NaN     NaN     NaN   
you belong to me                                       NaN     NaN     NaN   
zen and the art of motorcycle maintenance: an i...     NaN     NaN     NaN   
zoya                                                   NaN     NaN     NaN   

ID                                                  2977    3363    4017    \
title                                                                        
1984                                                   NaN     NaN     NaN   
1st to die: a novel                                    NaN     NaN     NaN   
2nd chance                                             NaN     NaN     NaN   
4 blondes                                              NaN     NaN     NaN   
\o\" is for outlaw"                                    NaN     NaN     NaN   
...                                                    ...     ...     ...   
wuthering heights                                      NaN     NaN     NaN   
year of wonders                                        7.0     NaN     NaN   
you belong to me                                       NaN     NaN     NaN   
zen and the art of motorcycle maintenance: an i...     NaN     0.0     NaN   
zoya                                                   NaN     NaN     NaN   

ID                                                  4385    6251    6323    \
title                                                                        
1984                                                   NaN     NaN     NaN   
1st to die: a novel                                    NaN     NaN     NaN   
2nd chance                                             NaN     NaN     NaN   
4 blondes                                              NaN     0.0     NaN   
\o\" is for outlaw"                                    NaN     NaN     NaN   
...                                                    ...     ...     ...   
wuthering heights                                      NaN     NaN     NaN   
year of wonders                                        NaN     NaN     NaN   
you belong to me                                       NaN     NaN     0.0   
zen and the art of motorcycle maintenance: an i...     NaN     0.0     NaN   
zoya                                                   NaN     NaN     NaN   

ID                                                  6543    ...  271705  \
title                                                       ...           
1984                                                   NaN  ...    10.0   
1st to die: a novel                                    9.0  ...     NaN   
2nd chance                                             0.0  ...     NaN   
4 blondes                                              NaN  ...     NaN   
\o\" is for outlaw"                                    NaN  ...     NaN   
...                                                    ...  ...     ...   
wuthering heights                                      NaN  ...     NaN   
year of wonders                                        0.0  ...     NaN   
you belong to me                                       NaN  ...     NaN   
zen and the art of motorcycle maintenance: an i...     NaN  ...     NaN   
zoya                                                   

In [43]:
pt.fillna(0,inplace=True)

In [44]:
pt.sample()

ID                                254     2276    2766    2977    3363    \
title                                                                      
the last time they met : a novel     0.0     0.0     0.0     0.0     0.0   

ID                                4017    4385    6251    6323    6543    ...  \
title                                                                     ...   
the last time they met : a novel     0.0     0.0     0.0     0.0     0.0  ...   

ID                                271705  273979  274004  274061  274301  \
title                                                                      
the last time they met : a novel     0.0     0.0     0.0     0.0     0.0   

ID                                274308  275970  277427  277639  278418  
title                                                                     
the last time they met : a novel     0.0     0.0     0.0     0.0     0.0  

[1 rows x 810 columns]

In [45]:
from scipy.sparse import csr_matrix

In [46]:
book_sparse= csr_matrix(pt)

In [47]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [48]:
from sklearn.neighbors import NearestNeighbors

In [49]:
model= NearestNeighbors(algorithm="brute")

In [50]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [51]:
distances, suggestions= model.kneighbors(pt.iloc[357, :].values.reshape(1,-1), n_neighbors=6)

In [52]:
distances

array([[ 0.        , 33.7934905 , 34.68429039, 34.87119155, 35.21363372,
        35.63705936]])

In [53]:
suggestions

array([[357, 175, 377, 356, 279, 307]], dtype=int64)

In [54]:
for i in range(len(suggestions)):
    print(pt.index[suggestions[i]])

Index(['notes from a small island', 'exclusive', 'pleading guilty',
       'no safe place', 'jacob have i loved', 'long after midnight'],
      dtype='object', name='title')


In [55]:
pt.index[54]

'at home in mitford (the mitford years)'

In [57]:
np.where(pt.index=='animal farm')[0][0]

47

In [58]:
def suggest_name(text):
    book_id=np.where(pt.index==text)[0][0]
    distances, suggestions= model.kneighbors(pt.iloc[book_id, :].values.reshape(1,-1), n_neighbors=6)
    
    for i in range(len(suggestions)):
        if i ==0:
            print("The suggestion for :", text ,"are")
        if not i:
            print(pt.index[suggestions[i]])

In [60]:
suggest_name("animal farm")

The suggestion for : animal farm are
Index(['animal farm', 'exclusive', 'jacob have i loved', 'pleading guilty',
       'second nature', 'winter moon'],
      dtype='object', name='title')


# MODEL 2

In [61]:
from sklearn.metrics.pairwise import cosine_similarity

In [62]:
similarity_score= cosine_similarity(pt)


In [65]:
similarity_score.shape

(704, 704)

In [100]:
def recommend(text):
    index=np.where(pt.index==text)[0][0]
#     distances= similarity_score(index)
    similar_items=sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1] ,reverse=True)[1:6]
    
    for i in similar_items:
        print(pt.index[i[0]])

In [101]:
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1] ,reverse=True)[1:6]

[(544, 0.26737808296485693),
 (82, 0.2634114351153846),
 (47, 0.2472046934739493),
 (633, 0.23506027537093593),
 (343, 0.22751706211226183)]

In [109]:
list(enumerate(similarity_score[0]))[1:6] # however it was arranged

[(1, 0.08410009916576991),
 (2, 0.0),
 (3, 0.0),
 (4, 0.03566519642188754),
 (5, 0.03968172992304222)]

In [111]:
sorted(list(enumerate(similarity_score[0])),reverse=True)[1:6] #arranged backwards

[(702, 0.10186330086460314),
 (701, 0.0),
 (700, 0.057664239460121704),
 (699, 0.0),
 (698, 0.0)]

In [113]:
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1] ,reverse=True)[1:6] #arranged according to second index

[(544, 0.26737808296485693),
 (82, 0.2634114351153846),
 (47, 0.2472046934739493),
 (633, 0.23506027537093593),
 (343, 0.22751706211226183)]

In [103]:
recommend('animal farm')

1984
angus, thongs and full-frontal snogging: confessions of georgia nicolson
midnight
lord of the flies
brave new world


In [116]:
pt.index[545]

"the hitchhiker's guide to the galaxy"

In [117]:
import pickle

In [118]:
pickle.dump(pt, open("pt.pkl", "wb"))
pickle.dump(books,open("books.pkl",'wb'))
pickle.dump(similarity_score,open("similarity_scores", 'wb'))